version: '3.8'
services:
  nginx:
    image: sfidanza/sharks-frontend
    ports:
      - "8080:8080"
    depends_on:
      - app
    labels:
      kompose.service.expose: "true"
    
  app:
    image: sfidanza/sharks
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - NODE_PORT=9090
    expose:
      - 9090
    depends_on:
      - mongo

  mongo:
    image: mongo:4-focal
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  admin:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    labels:
      kompose.service.expose: "true"
    
volumes:
  mongodb: